spring:
  data:
    neo4j:
      username: neo4j
      password: admin


logging:
  level:
    org:
      neo4j:
        ogm:
          drivers:
            bolt:
              request:
                BoltRequest: DEBUG
